# Generated by Django 5.0.5 on 2024-05-07 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="adress",
            new_name="address",
        ),
    ]
